name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "18"

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: npm install pnpm && pnpm install

      # 运行生成入口文件
      - name: Build src index.js 文件
        run: yarn gen

      # 打包为 docs
      - name: Build docs site
        run: yarn docs

      # 打包为 playground
      - name: Build playground site
        run: pnpm play:build
      # 移动文件夹
      - name: Move playground to docs
        run: mv playground/dist docs/playground

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
          # 部署到 gh-pages 分支
          BRANCH: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          FOLDER: docs/
